package main

import (
	"path/filepath"
)

// GenerateAuth produces the sign-in screens in the project.
//
// This is the starter kit, and it follows the Breeze contract literally: it
// publishes views, routes and handlers into the project and gets out of the way.
// Nothing here is a runtime dependency, and every file is yours to edit the
// moment it lands.
//
// It is a command rather than a package to import, because an imported starter
// kit cannot be edited -- and editing the sign-in screen is the first thing
// anyone does. It is a command rather than a repository to clone, because the
// generator already exists and a second delivery mechanism would be a second way
// to do one thing (RULE 9).
func GenerateAuth(m Module) ([]File, error) {
	if m.ModulePath == "" {
		return nil, errModulePath
	}

	// The controllers, in the Laravel tree. `php artisan ui bootstrap --auth`
	// puts them under app/Http/Controllers/Auth, and so do we.
	var out []File
	for _, t := range []struct {
		path string
		tmpl string
	}{
		{filepath.Join("app", "Http", "Controllers", "Auth", "LoginController.go"), authModuleTemplate},
		{filepath.Join("app", "Http", "Controllers", "Auth", "LoginController_handlers.go"), authHandlersTemplate},
		// HomeController comes with the kit, exactly as `php artisan ui
		// bootstrap --auth` generates it.
		//
		// It is not optional here. A page renders with its layout's type, so
		// replacing the layout replaces what home passes -- and the skeleton's
		// controller, still handing over the struct its own view used to
		// declare, stops compiling. The controller and the view it renders are
		// one unit, and the kit owns both.
		{filepath.Join("app", "Http", "Controllers", "HomeController.go"), authHomeControllerTemplate},
	} {
		content, err := render(filepath.Base(t.path), t.tmpl, m)
		if err != nil {
			return nil, err
		}
		out = append(out, File{Path: t.path, Content: content})
	}

	// And the nine views, which are the point of the command: the same nine
	// `laravel/ui` generates, at the same paths, with the same job. What
	// changes is what is inside them -- kyse instead of Blade, Tailwind instead
	// of Bootstrap, HTMX instead of jQuery (ADR 0022).
	out = append(out, AuthViews()...)
	return out, nil
}

const authManifestTemplate = `# What this module declares about itself.
#
# ` + "`aru doctor`" + ` checks these against the code. The sign-in screens talk to
# the auth service and to the session store, and nothing else: no outbound call,
# no file, no subprocess, and no table of their own -- the users table belongs to
# the framework's auth module.

name = "your-org/authui"
framework = ">= 0.6"
profiles = ["conventional"]

[permissions]
network = false
filesystem = false
exec = false
migrations = false
`

const authModuleTemplate = `// Package authui holds the sign-in screens.
//
// Generated by ` + "`aru make:auth`" + `, and yours from this moment on: edit it, delete
// what you do not want, restyle it. Nothing in the framework imports it back.
//
// The authentication itself stays in the framework's auth module -- password
// verification, the timing-equalized failure path, session rotation. This package
// owns what a screen owns, which is the markup and the two handlers that drive it.
package authui

import (
	"github.com/arandu-io/framework/httpx"
	"github.com/arandu-io/framework/kernel"
	"github.com/arandu-io/framework/modules/auth"
	"github.com/arandu-io/framework/security"
)

// Module registers the screens.
//
// It composes the framework's auth module instead of replacing it. Replacing it
// took the users table out of the schema: this kit declares no table of its own
// -- deliberately, because two owners for one table is how a rollout deadlocks
// -- so a wiring list with this module and without the framework's had nothing
// left to create users, and the seeder that makes the first administrator ran
// against a database with no such table.
//
// Embedding it means the schema, the health check and anything the framework
// adds to that module arrive with this one. What the kit takes over is Routes,
// and only Routes: the published screens answer where the minimal ones did.
type Module struct {
	// The framework's auth module. It is the owner of the users table, and it
	// stays the owner.
	*auth.Module

	auth     *auth.Service
	sessions *security.SessionStore
	csrf     *security.CSRF
	tenant   auth.TenantResolver
}

// New returns the module.
//
// Register it INSTEAD of auth.New: this one already carries what auth.New
// returns, and both answer /auth/login. Registering both is a duplicate route
// and a table with two owners.
//
// The session store and the CSRF issuer are passed in rather than reached
// through the service, because a screen is allowed to know about a token and a
// cookie, and the service is not allowed to expose its own dependencies.
func New(svc *auth.Service, sessions *security.SessionStore, csrf *security.CSRF, tenant auth.TenantResolver) *Module {
	if tenant == nil {
		tenant = auth.FixedTenant("")
	}
	return &Module{
		Module:   auth.New(svc, tenant),
		auth:     svc,
		sessions: sessions,
		csrf:     csrf,
		tenant:   tenant,
	}
}

// Compile-time proof that the module honors the contracts it claims. The second
// line is the one that matters here: it is what stops a refactor that drops the
// embedded module and takes the users table down with it.
var (
	_ kernel.Module     = (*Module)(nil)
	_ kernel.Migratable = (*Module)(nil)
)

// Name is the module identifier. The routes below are this package's, so the
// route table names this package rather than the framework's.
func (m *Module) Name() string { return "authui" }

// Routes registers the screens, in place of the framework's.
//
// This is the one method the kit overrides. The embedded module still declares
// the users table; it just no longer answers /auth/login, because this does.
func (m *Module) Routes(r *httpx.Router) {
	g := r.Group("/auth")
	g.Get("/login", m.showLogin)
	g.Post("/login", m.doLogin)
	g.Post("/logout", m.doLogout)

	// arandu:begin custom
	// Registration, password reset and anything else you add go here.
	// arandu:end custom
}
`

const authHandlersTemplate = `package authui

import (
	"errors"
	"net/http"

	"github.com/arandu-io/framework/httpx"
	"github.com/arandu-io/framework/modules/auth"
	"github.com/arandu-io/framework/observability"
	"github.com/arandu-io/framework/validation"
	"github.com/arandu-io/framework/view"

	"{{.ModulePath}}/resources/views"
)

// Handlers are thin on purpose: extract the input, delegate to the service,
// render. No business rule and no repository access lives here -- ` + "`aru doctor`" + `
// complains when a handler imports the data package.

// showLogin renders the form with a fresh CSRF token.
func (m *Module) showLogin(w http.ResponseWriter, r *http.Request) {
	token, err := m.csrf.Issue(m.sessions.IDFromRequest(r))
	if err != nil {
		observability.Log(r.Context()).Error("issuing csrf token", "error", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}

	// The renderer sets the content type and records the render on the
	// puts the render on the request timeline. Calling Render directly leaves
	// the template column at zero, which says the view is free when nobody
	// measured it.
	data := views.AuthPage{
		Page: views.Page{
			AppName:  "{{.ModulePath}}",
			Title:    "Sign in",
			Token:    token,
			LoginURL: "/auth/login",
		},
	}
	if err := view.NewRenderer().Render(r.Context(), w, http.StatusOK, "auth.login", data); err != nil {
		observability.Log(r.Context()).Error("rendering the sign-in page", "error", err)
	}
}

// doLogin authenticates and rotates the session.
//
// On failure it re-renders the form with the message inline, which is the whole
// shape of validation on this stack: the server rejects, and the same response
// carries the reason. Nothing is validated twice in the browser.
func (m *Module) doLogin(w http.ResponseWriter, r *http.Request) {
	in := auth.LoginRequest{
		Email:    r.PostFormValue("email"),
		Password: r.PostFormValue("password"),
	}
	if errs := in.Validate(); errs.Any() {
		m.rejected(w, r, in.Email, errs, http.StatusUnprocessableEntity)
		return
	}

	// The tenant comes from the application, never from the request: a form
	// field here would let anyone pick which tenant to authenticate against.
	u, err := m.auth.Authenticate(r.Context(), m.tenant(r), in.Email, in.Password)
	if err != nil {
		if errors.Is(err, auth.ErrInvalidCredentials) {
			// One message for both halves. Saying which one was wrong turns this
			// endpoint into an account enumeration oracle.
			m.rejected(w, r, in.Email, validation.Errors{
				"email": {"invalid email or password"},
			}, http.StatusUnauthorized)
			return
		}
		observability.Log(r.Context()).Error("login failed", "error", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}

	// Rotating the id is mandatory here: keeping the pre-login session is
	// session fixation, and ` + "`aru doctor`" + ` checks that this call exists.
	old := m.sessions.IDFromRequest(r)
	if _, err := m.sessions.Rotate(r.Context(), w, old, auth.SubjectOf(u)); err != nil {
		observability.Log(r.Context()).Error("starting session", "error", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}

	redirect(w, r, "/")
}

// doLogout destroys the session on the server, not only in the browser.
func (m *Module) doLogout(w http.ResponseWriter, r *http.Request) {
	if err := m.sessions.Destroy(r.Context(), w, m.sessions.IDFromRequest(r)); err != nil {
		observability.Log(r.Context()).Error("destroying session", "error", err)
	}
	redirect(w, r, "/auth/login")
}

// redirect answers the way the request asked to be answered.
//
// The form is submitted two ways on purpose: hx-post when HTMX is running, and
// method="post" when it is not -- that is the path without JavaScript, and it is
// the one that has to keep working. HX-Redirect is a header only HTMX reads, so
// answering it to a plain form post is 200 with an empty body: a blank page
// after a login that succeeded, with nothing in the log to say so.
//
// httpx.Context is where that branch already lives -- HX-Redirect for an HTMX
// request, 303 with a Location for everything else. Restating it here would be a
// second way to redirect, and the second one is the one that drifts (RULE 9).
func redirect(w http.ResponseWriter, r *http.Request, to string) {
	if err := (&httpx.Context{Response: w, Request: r}).Redirect(to); err != nil {
		observability.Log(r.Context()).Error("redirecting", "error", err, "to", to)
	}
}

// rejected re-renders just the form, which is what HTMX swaps back in.
//
// The token is reissued because the session id may have changed, and the email
// is kept because retyping it after a rejection is the fastest way to make a
// login screen unpleasant. The password never comes back.
func (m *Module) rejected(w http.ResponseWriter, r *http.Request, email string, errs validation.Errors, status int) {
	token, err := m.csrf.Issue(m.sessions.IDFromRequest(r))
	if err != nil {
		observability.Log(r.Context()).Error("issuing csrf token", "error", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}

	// The status is explicit: HTMX swaps the body of a 422 and of a 200 alike,
	// so answering 200 for a rejection would make the browser, the logs and
	// every metric agree that it worked.
	form := views.AuthPage{
		Page: views.Page{
			AppName:  "{{.ModulePath}}",
			Title:    "Sign in",
			Token:    token,
			LoginURL: "/auth/login",
		},
		Email:      email,
		EmailError: errs.First(),
	}
	if err := view.NewRenderer().Render(r.Context(), w, status, "auth.login", form); err != nil {
		observability.Log(r.Context()).Error("rendering the form", "error", err)
	}
}

// arandu:begin custom
// Your own handlers go here.
// arandu:end custom
`

// The views are no longer here. `aru make:auth` writes the nine of
// `laravel/ui` in resources/views, as kyse — see authviews.go and ADR 0022.

// authHomeControllerTemplate is the HomeController the kit publishes, the same
// file `php artisan ui bootstrap --auth` generates.
//
// The constructor takes the session store and the CSRF issuer, which the
// skeleton's did not: the layout this command installs draws a sign-out form and
// puts the token in hx-headers, and a controller that cannot read the session
// renders a landing page that says "Login" to somebody who just signed in, with
// an empty token that makes the next write fail the CSRF check. That is one line
// of wiring in bootstrap/app.go, and make:auth prints it -- the same shape
// `aru make:module` uses for every controller it writes.
const authHomeControllerTemplate = `package controllers

import (
	"github.com/arandu-io/framework/httpx"
	"github.com/arandu-io/framework/security"

	"{{ .ModulePath }}/resources/views"
)

// HomeController answers the landing page.
//
// It renders with views.AuthPage, the struct layouts/app declares: a page that
// declares no data of its own renders with its layout's struct, so every screen
// of the kit shares this one. A field this page does not use stays at its zero
// value.
type HomeController struct {
	Controller

	// appName is what the page is titled. It arrives through the constructor
	// rather than through a global read: a controller that reads the
	// environment is a controller no test can pin.
	appName string

	// sessions and csrf are what the chrome is drawn from: who is signed in,
	// and the token every write of this session carries. They arrive through
	// the constructor for the same reason appName does, and they are the same
	// two every controller ` + "`aru make:module`" + ` writes takes -- a screen is
	// allowed to know about a token and a cookie.
	sessions *security.SessionStore
	csrf     *security.CSRF
}

// NewHomeController returns the controller. bootstrap/app.go builds it and hands
// it to the routes.
func NewHomeController(appName string, sessions *security.SessionStore, csrf *security.CSRF) *HomeController {
	return &HomeController{appName: appName, sessions: sessions, csrf: csrf}
}

// Compile-time proof that this controller answers GET / the way Resource and the
// route table expect. It costs nothing and catches a renamed method.
var _ httpx.Indexer = (*HomeController)(nil)

// Index renders the landing page.
//
// The session and the token are read above the custom block, and deliberately:
// they are what the layout draws its navigation and its hx-headers from, so a
// regeneration that carried over an edited block would otherwise carry over a
// page that greets a signed-in visitor with a sign-in link.
func (c *HomeController) Index(ctx *httpx.Context) error {
	// Who is signed in, from the session cookie and never from the request. An
	// error here is the anonymous case -- no cookie, a forged one, or a session
	// that expired -- and the guest half of the navigation is what gets drawn.
	subject, err := c.sessions.Load(ctx.Ctx(), ctx.Request)
	signedIn := err == nil

	// The token reaches the markup twice: the hidden field of the sign-out form
	// and the hx-headers attribute on <body>. A page rendered without one
	// answers 200 and then refuses the next write with 419, which reads like a
	// broken session rather than a missing field.
	token, err := c.csrf.Issue(c.sessions.IDFromRequest(ctx.Request))
	if err != nil {
		return err
	}

	// arandu:begin custom
	return ctx.View("home", views.AuthPage{
		// views.Page is the state the layout draws, embedded rather than
		// repeated. The navigation draws a link only for what answers: the kit
		// ships the sign-in handler and nothing else, so RegisterURL stays
		// empty and the link is not drawn -- a link to a route nobody
		// registered is a 404 the layout put there.
		Page: views.Page{
			AppName:       c.appName,
			Title:         c.appName,
			Token:         token,
			Authenticated: signedIn,
			// The identifier, because that is what a session carries. Show a
			// display name here once you have a screen that loads the user
			// through its policy.
			UserName:  subject.ID,
			HomeURL:   "/",
			LoginURL:  "/auth/login",
			LogoutURL: "/auth/logout",
		},

		// Password reset stays off for the same reason: write the handler, then
		// turn the link on.
		HasPasswordReset: false,
	})
	// arandu:end custom
}
`
